### ISSUE TITLE
金钱同步问题

### ISSUE THREAD

**Issue by pianwan** [YiC200333/XConomy#43]
在以下情况下，玩家的钱不会被正确同步。

玩家A在服务器A
玩家B正在服务器B

这时候玩家A在A服给予B一定钱 A输入/pay B 1
然后B玩家在B服金钱并不会改变，按照原来的金钱操作。

如果开启cache-correction: true
则会出现另一个问题，假定B玩家的钱不足100，而A服中B玩家的钱暂时大于120（还未同步）
如果A服的A玩家输入/eco take B 120
此时B服的B玩家的钱将会是 -20

**Comment by YiC200333** [comment]
BC端有安装插件吗？

**Comment by pianwan** [comment]
> BC端有安装插件吗？

有的，很正常的安装了。

**Comment by YiC200333** [comment]
可以给下你服务器版本和插件版本吗？
可以的话，加下群，方便反馈，谢谢

**Comment by pianwan** [comment]
A 服
```
Settings:
  language: Chinese
  check-update: false
  refresh-time: 600
  eco-command: true
  disable-essentials: true
  initial-bal: 0
  ranking-size: 10
  non-player-account: false
  cache-correction: false
  transaction-record: true
  semi-online-mode: false
  username-ignore-case: false
  lines-per-page: 5


Currency:
  singular-name: *
  plural-name: *
  integer-bal: false
  thousands-separator: ','
  display-format: '%balance% %currencyname%'
  max-number: '10000000000000000'
BungeeCord:
  enable: true
  sign: a

```
B 服
```
Settings:
  language: Chinese
  check-update: false
  refresh-time: 600
  eco-command: true
  disable-essentials: true
  initial-bal: 0
  ranking-size: 10
  non-player-account: false
  cache-correction: false
  transaction-record: true
  semi-online-mode: false
  username-ignore-case: false
  lines-per-page: 5


Currency:
  singular-name: *
  plural-name: *
  integer-bal: false
  thousands-separator: ','
  display-format: '%balance% %currencyname%'
  max-number: '10000000000000000'
BungeeCord:
  enable: true
  sign: b
```

bungeecord端加插件，AB再加vault

重复以上过程即可

我是本地开两个服测试的，插件是构建的最新版， paper1.17.1
