### ISSUE TITLE
进入服务器后被踢出，提示UUID mismatch

### ISSUE THREAD

**Issue by WitheredWinter** [YiC200333/XConomy#86]
**Version of XConomy**  
XConomy V2.19.5

**Server version**  
Paper 1.16.5;Paper 1.19.3

**Storage-type**  
SQLite ; MySQL  (BOTH)

**Describe the issues**  
是BC服，一开始在BC端关闭了正版验证，用该账号进入游戏；后来开启了正版验证，再用同一账号进入游戏时被踢出，提示UUID 

---

**XConomy's config.yml**

```
#Default Online Offline SemiOnline
#Default mode will automatically detect the player's UUID(support GeyserMC)
#Online mode is better for servers that enable online-mode(support Yggdrasil)
#Offline mode does not support ignoring username case
#If you use floodgate(GeyserMC) and the option 'username-prefix' is set to empty, Please use SemiOnline mode
UUID-mode: Offline
#In convertion mode, can use command '/xconomy' import data from other plugins based on Vault
#Conflicting data will be skipped, The imported data will be saved in XConomy/importdata/data.yml
#In this mode, XConomy will not start normally
#After the conversion, please check data and turn off this mode
#Sponge version does not have this function
importdata-mode: false


#Settings
Settings:
  #Chinese ChineseTW English French Spanish Russian Turkish Japanese German
  #Indonesia Portuguese Italian
  language: Chinese
  #Whether to check for new version
  check-update: true
  #TOP10 and the Server Total refresh time interval (Seconds)
  refresh-time: 300
  #If set to true, XConomy will register the following commands:
    # - economy
    # - eco
    # - ebalancetop
    # - ebaltop
    # - eeconomy
  #Please keep in mind that if Essentials is installed on your server
  #XConomy will take over these commands.
  eco-command: true
  #XConomy will disable the economic function of Essentials.
  #Just the economic function.
  disable-essentials: true
  #Initial balance
  initial-bal: 0
  #Tax to be paid for pay command (0.5 means 50%, 1 means 100%)
  payment-tax: 0
  #Ranking size (Max value 100)
  ranking-size: 10
  #Rows per page of list (Ranking and help menu)
  lines-per-page: 5
  #If you need to modify the data in the database directly, it is recommended to enable it
  #Asynchronous saving of data is not supported after caching is disabled
  #Disabling caching will increase the pressure on the database
  disable-cache: false
  #Dose save transaction record
  #Only MySQL is supported
  transaction-record: true
  #Record transaction information of pay command while player offline.
  #The player will receive tips when they reconnect.
  #Transaction-record function must be enabled.
  offline-pay-transfer-tips: false
  #Ignore the case of player names
  username-ignore-case: false


#It can solve the problem that some plugins need to create non-player accounts, such as Factions
#==========================================================================================
#Plugins supported by default (no requirement to enable non-player-account)
#Towny
#==========================================================================================
#Non-player account data is not synced with BC
non-player-account:
  #Whether to enable non-player accounts.
  enable: false
  #If the account name contains fields in the whitelist, it will be recognized as non-player accounts.
  #Otherwise, it is recognized as a player account
  #If the player's name contains fields in the whitelist, it will be denied access to the server.
  #This function can reduce the times that reading data from the database.
  whitelist:
    #Whether to enable whitelist.
    enable: false
    fields-list:
      - tax
      - nation-


#The display of the currency
Currency:
  singular-name: dollar
  plural-name: dollars
  #Is the balance an integer
  integer-bal: false
  thousands-separator: ','
  #%format_balance% indicate the balance after the format
  display-format: '%balance% %currencyname%'
  #Maximum amount (default is maximum)
  max-number: '10000000000000000'
  format-balance:
    1000: k
    1000000: m
    1000000000: b


#BungeeCord settings
BungeeCord:
  #Whether to enable BungeeCord synchronization
  #After BungeeCord sync is turned on, the console and other plugins will not be able to modify the balance in the server without player
  #Please Set bungeecord to true in the spigot.yml
  enable: false
  #Server ID, keep the ID and the MySQL settings is the same between the servers requiring synchronization
  sign: main
```

**Logs**
```
[15:35:30 INFO]: WinterArchon lost connection: [XConomy] UUID mismatch
Username - WinterArchon
UUID[C] - fd5be743-289e-4bc7-96e0-fef24825743a
UUID[O] - f3bae41f-b0f7-372b-9279-f131df31e0b8
[15:35:30 INFO]: - WinterArchon 离开了
```
